### ISSUE TITLE
Titlebar buttons on Windows 10 are malformed when menu bar is enabled

### ISSUE THREAD

**Issue by stepcity** [bmFtZQ/Edge-FrFox#1]
Firstly this is really great and I haven't seen much community contribution in it but it's gotten to the point where it's my daily driver theme.

On to the issue: When I enable the menubar, the titlebar buttons move higher up and are cut off. 
![This is a screenshot of what it looks like normally:](https://user-images.githubusercontent.com/67624345/111919044-2c90dd80-8a45-11eb-8a39-e4faf228908f.png)
![This is a screenshot of what it looks like with the menubar enabled:](https://user-images.githubusercontent.com/67624345/111919057-387c9f80-8a45-11eb-9eb0-eb64dcde33cf.png)

I haven't looked through the code so I don't know what the cause/solution could be, but it'd be great if it was fixed since I prefer using the menubar.

**Comment by bmFtZQ** [comment]
This is now fixed for the latest release.

There were negative margins that aligned the buttons to the top (which were used to align the buttons to the top of the screen) , but they were never meant to be applied to the menubar title buttons.
