### ISSUE TITLE
Pinned tabs hiding behind upinned tabs if tab strip is scrollable

### ISSUE THREAD

**Issue by Ichicoro** [bmFtZQ/edge-frfox#100]
**Description**
Any pinned tab will get pushed behind unpinned tabs if the tab scroll arrow icons are visible

**Include screenshot / video recording if possible.**
<img width="286" alt="image" src="https://github.com/bmFtZQ/edge-frfox/assets/21175939/c5dd073d-45e8-4242-9ebf-bbefdec94cab">
<img width="276" alt="image" src="https://github.com/bmFtZQ/edge-frfox/assets/21175939/cd2d2c12-6954-4355-9f1d-d8579ee367ed">

**Configuration**
- Firefox Version: Firefox Nightly 109.0a
- OS: macOS Ventura 13.2

**Comment by bmFtZQ** [comment]
This should be fixed in the latest commit.
