### ISSUE TITLE
Context menu item issue with incomplete font display.

### ISSUE THREAD

**Issue by iWakuo** [bmFtZQ/edge-frfox#102]
<img width="47" alt="Snipaste_2023-09-23_15-32-09" src="https://github.com/bmFtZQ/edge-frfox/assets/62334532/8f2db3b6-6b6d-446e-927c-03c125a2b38b">
<img width="71" alt="Snipaste_2023-09-23_15-31-33" src="https://github.com/bmFtZQ/edge-frfox/assets/62334532/cfbcece0-58a9-44de-9b15-f2e2c4c1d2c2">

<img width="91" alt="Snipaste_2023-09-23_15-32-22" src="https://github.com/bmFtZQ/edge-frfox/assets/62334532/a549e695-dfe8-436b-b945-ecbc04d7c230">
<img width="105" alt="Snipaste_2023-09-23_15-32-36" src="https://github.com/bmFtZQ/edge-frfox/assets/62334532/ce996cc6-7b4b-4460-9552-f0bb8c89f0ed">

On the left is the normal case, on the right is the case of using the look theme, how do I adjust the width of the text display inside the menu item?

**Comment by bmFtZQ** [comment]
Could you test the latest commit of the theme? Based on my own testing, it should work properly now.

**Comment by iWakuo** [comment]
> Could you test the latest commit of the theme? Based on my own testing, it should work properly now.

<img width="120" alt="PixPin_2023-12-03_14-56-56" src="https://github.com/bmFtZQ/edge-frfox/assets/62334532/62f494a7-5a73-4b66-88dc-627b745b71c4">
It's  already  displaying  normally,  I  love  you  so  much!
