### ISSUE TITLE
"System theme — auto" is completely broken in Firefox 119

### ISSUE THREAD

**Issue by jobsrobson** [bmFtZQ/edge-frfox#106]
**Description**
In Firefox 119, using the latest version of Edge-Frfox (commit eba1454), the 'System theme — auto' theme is completely broken when the system is in dark mode. The other default themes (always 'Dark' and 'Light') work normally. The problem started to happen after updating Firefox to version 119.0.

How to reproduce: being on Firefox 119 and with the latest version of Edge-Frfox installed, use 'System theme — auto' and activate the Windows dark theme. Note that Firefox remains with light background colors and the fonts and icons change to white, making the browser impossible to use.

![Captura de Tela (58)](https://github.com/bmFtZQ/edge-frfox/assets/60002861/7db59fa7-fb0d-4df4-aeb2-338ebf99d9ca)

![Captura de Tela (59)](https://github.com/bmFtZQ/edge-frfox/assets/60002861/8b567298-ed6c-4af7-9ec8-2e5a256c76d4)

**about:config flags**
- toolkit.legacyUserProfileCustomizations.stylesheets: True
- svg.context-properties.content.enabled: True
- layout.css.color-mix.enabled: True
- layout.css.light-dark.enabled: True
- uc.tweak.hide-newtab.logo: True
- uc.tweak.floating-tabs: True

**Configuration**
- Firefox Version: 119.0 (64-bits)
- OS: Windows 11 (22635.2552)

**Comment by bmFtZQ** [comment]
This is an issue with the floating tabs tweak, I will try to fix it. But in the meantime, disabling the floating tabs tweak should temporarily fix this.

**Comment by bmFtZQ** [comment]
This should be fixed now. I forgot to apply the same changes I made to the normal theme colours for Firefox 119 to the floating tabs tweak.

**Comment by jobsrobson** [comment]
Fixed! Thank you!
