### ISSUE TITLE
Light Theme when it should be Dark Theme

### ISSUE THREAD

**Issue by SleepDaemon** [bmFtZQ/edge-frfox#108]
**Description**
Just simply follow the steps to install it. 

**Include screenshot / video recording if possible.**
![image](https://github.com/bmFtZQ/edge-frfox/assets/88533953/e83fbbc8-ad85-41b5-9f49-f4101f6c285f)

**Configuration**
- Firefox Version: 119.0.1
- OS: Windows 11 23H2

**Comment by bmFtZQ** [comment]
I cannot replicate this on my system.

Are you using the [latest version](https://github.com/bmFtZQ/edge-frfox/archive/refs/heads/main.zip) of the theme?

Do you have the preference `layout.css.light-dark.enabled` set to true?

What tweaks do you have enabled?

**Comment by SleepDaemon** [comment]
> I cannot replicate this on my system.
> 
> Are you using the [latest version](https://github.com/bmFtZQ/edge-frfox/archive/refs/heads/main.zip) of the theme?
> 
> Do you have the preference `layout.css.light-dark.enabled` set to true?
> 
> What tweaks do you have enabled?

I am using latest version, I do have that config set to true, and I am using [BetterFox](https://github.com/yokoffing/BetterFox) tweaks.

**Comment by bmFtZQ** [comment]
Still can't replicate this, could you try in a new profile only installing the theme?

**Comment by SleepDaemon** [comment]
> Still can't replicate this, could you try in a new profile only installing the theme?

Still having it

![image](https://github.com/bmFtZQ/edge-frfox/assets/88533953/6d04e215-4352-4cca-8bfa-8e3fa351f0c6)

**Comment by SleepDaemon** [comment]
Ok I've just tried it without the other tweaks from betterfox, like i removed it. Still having that problem so it is not that causing the problem.

**Comment by SleepDaemon** [comment]
Ah ok, I downloaded the zip from releases. When I should downloaded from here:
![image](https://github.com/bmFtZQ/edge-frfox/assets/88533953/dc8cec50-c689-449c-be54-c22bd2ec6842)

**Comment by bmFtZQ** [comment]
Did that fix it? The version from the releases is quite outdated at the moment.

**Comment by SleepDaemon** [comment]
> Did that fix it? The version from the releases is quite outdated at the moment.

Yes using the one from releases is broken, I suggest create a new release so someone else doesnt run into same issue or others.

**Comment by bmFtZQ** [comment]
Okay, I will create a new release now, I haven't updated that in a while.
