### ISSUE TITLE
Broken tab background color on Firefox Developer Edition.

### ISSUE THREAD

**Issue by aspizu** [bmFtZQ/edge-frfox#110]
using Firefox Developer Edition 121.0b2 (64-bit) on Windows 11 with 30a20c3edbc2190a251721ff482392e6c65b8bed

![](https://media.discordapp.net/attachments/985170415343267880/1176958605270986804/image.png?ex=6570c31e&is=655e4e1e&hm=9e8cc2f3ca490278612b1b7c311c6c3244fb5417948f747bbb3bf197948d6b92&=&format=webp&width=1466&height=464)

This occurs only with the default system/auto theme.

`uc.tweak.force-tab-colour` has no effect.

**Comment by bmFtZQ** [comment]
This should be fixed in the newest commit of the theme.
