### ISSUE TITLE
Bug in inactive tab when hovered.

### ISSUE THREAD

**Issue by aspizu** [bmFtZQ/edge-frfox#111]
![](https://media.discordapp.net/attachments/1125852570531942430/1177296828857852075/image.png?ex=6571fe1d&is=655f891d&hm=0ef0fe62217ecb48fbc0ddc8aef87094b140641d61daebd7158d8a6873ca2f7e&=&format=webp&width=1432&height=322)

**Comment by bmFtZQ** [comment]
This should be fixed in the latest commit of the theme.

**Comment by aspizu** [comment]
Thank you!
