### ISSUE TITLE
Checkboxes has both ticked and filled state on Linux

### ISSUE THREAD

**Issue by bbhtt** [bmFtZQ/edge-frfox#113]
**Description**

Checkboxes has both ticked and filled state on Linux

**Include screenshot / video recording if possible.**

![image](https://github.com/bmFtZQ/edge-frfox/assets/62639087/03f491ca-e281-4f15-98b9-480d05f09c1a)

**Configuration**
- Firefox Version: 122
- OS: (eg. Windows, macOS, etc.) Linux Fedora 39

**Comment by bbhtt** [comment]
Same as https://github.com/edelvarden/material-fox-updated/commit/b9393bd9bb3a304258c2493cd95abf18bfb9e9a2

**Comment by bmFtZQ** [comment]
This should be fixed now in the latest commit of the theme.
