### ISSUE TITLE
Rounded page corners

### ISSUE THREAD

**Issue by aspizu** [bmFtZQ/edge-frfox#117]
### Screenshot from Edge:
![](https://media.discordapp.net/attachments/985170415343267880/1181891811158007888/image.png?ex=6582b586&is=65704086&hm=00bdd321bd3b686be91f13a01e6a3241be2bdc2214cd0711de5fdd0e2b242610&=&format=webp&quality=lossless&width=614&height=748)

### Description:

Round the corners of the page.

**Comment by bmFtZQ** [comment]
You can already use the `uc.tweak.rounded-corners` tweak to do this.

![image](https://github.com/bmFtZQ/edge-frfox/assets/62812711/62e3cebe-98c3-4095-8e84-3736c386afc5)
