### ISSUE TITLE
Private window does not follow Firefox dark mode colours

### ISSUE THREAD

**Issue by bbhtt** [bmFtZQ/edge-frfox#119]
### Description

See the difference in the toolbar/tabsbar and menus

![image](https://github.com/bmFtZQ/edge-frfox/assets/62639087/7e9f2d81-ac19-4615-a79c-0525b4b14091)

### Configuration
* Firefox Version: 121
* OS: (eg. Windows 11, macOS 14, Linux with GNOME 45, etc.) Fedora 39
* Tweaks enabled: 
  * `uc.tweak.floating-tabs`
  * `uc.tweak.disable-drag-space`
  * `uc.tweak.rounded-corners`
  * `uc.tweak.show-tab-close-button-on-hover`

**Comment by bmFtZQ** [comment]
This should be fixed in the latest release.

**Comment by bbhtt** [comment]
Thanks, seems to work!
