### ISSUE TITLE
Update URL bar dropdown border color to more closely match Edge's theme

### ISSUE THREAD

**Issue by marioparty26** [bmFtZQ/edge-frfox#123]
### Description
First of all, thank you so much for continuously supporting this. 
This theme is just beyond perfect.

One suggestion/request for the URL Bar Dropdown Box ...

In Firefox Theme - Dropdown box has grey border on right and bottom
Edge - Dropdown box does not have this right and bottom border

Is it possible to update the URL dropdown box so that its right and bottom borders styling more closely match Edge's style?

### Screenshots
Firefox:
![image](https://github.com/bmFtZQ/edge-frfox/assets/47206815/ae57b8f0-f9b4-4139-af22-fbf03ffd0885)

Edge:
![image](https://github.com/bmFtZQ/edge-frfox/assets/47206815/0e56c6d4-6268-4f61-bd34-362a847df8d8)

**Comment by bmFtZQ** [comment]
I believe this is just a UI bug with fractional scaling on Edge as it seems you have a UI scale of 150% set.

At 100% scale, the border appears on all sides of the URL bar drop-down in Edge:
![Edge URL bar screenshot showing border on all sides at 100% UI scale.](https://github.com/bmFtZQ/edge-frfox/assets/62812711/bda2d14f-caa4-44e0-9fa7-8be235929b4c)

With some further testing, at 175% UI scale all sides except the bottom have the border:
![Edge URL bar screenshot showing border on all sides except the bottom at 175% UI scale.](https://github.com/bmFtZQ/edge-frfox/assets/62812711/e44f1e3d-7747-4254-b052-5d1e32ac8554)

150% UI scale does indeed have a missing border on the right and bottom:
![Edge URL bar screenshot showing missing border on the right and bottom at 150% UI scale.](https://github.com/bmFtZQ/edge-frfox/assets/62812711/54447723-ec41-461d-8231-df3302aa37ba)

125% UI scale has the border on all sides of the URL bar drop-down:
![Edge URL bar screenshot showing border on all sides at 125% UI scale.](https://github.com/bmFtZQ/edge-frfox/assets/62812711/14aae538-cb9b-45b3-a62f-51555a69210d)
