### ISSUE TITLE
Theme conflicts with GTK themes on Linux

### ISSUE THREAD

**Issue by aspizu** [bmFtZQ/edge-frfox#125]
### Description

There are small bugs or inconsistencies on Linux. Changing the firefox theme fixes some of them.

![](https://media.discordapp.net/attachments/871004796667170906/1191033739384467527/image.png?ex=65a3f79b&is=6591829b&hm=84532c73ce297318f6e5b9ccdb79df8ea3c2240987f8143966b650a2bde23be8&=&format=webp&quality=lossless&width=1552&height=698)

### Known Bugs
 - Checkbox and Radio buttons have conflicting styles.
 - When combined with the adw-gtk3 theme, window has square outline on corners but background is rounded.
 - Bookmark icon is black colored.

Using the adw-gtk3 works well, seems to look better than default Adwaita.

### Configuration
* Firefox Version: Firefox Developer Edition 122.0b4 (64-bit)
* OS: Arch Linux (Cachy OS)
* Tweaks enabled: 
  * `force-tab-colour`

**Comment by bmFtZQ** [comment]
This should be fixed now in the latest commit of the theme.

**Comment by aspizu** [comment]
pls give option to have system checkbox styling

**Comment by bmFtZQ** [comment]
I have changed it, now on Linux the custom checkbox icon will just be hidden instead, with the original icon displayed.
