### ISSUE TITLE
primary dialog button has no background

### ISSUE THREAD

**Issue by aspizu** [bmFtZQ/edge-frfox#126]
![](https://media.discordapp.net/attachments/271011976929345537/1191313225082482688/image.png?ex=65a4fbe6&is=659286e6&hm=79a3cd937ea870b451bf04d812a8b7b83066fd5dffed63a91c27d15d01ea89a0&=&format=webp&quality=lossless&width=2160&height=876)

**Comment by bmFtZQ** [comment]
I was already working on this before this issue, but now the GTK theme is updated in the latest commit.

**Comment by aspizu** [comment]
thank you
