### ISSUE TITLE
Add spacing above tabs in fullescreen mode

### ISSUE THREAD

**Issue by SleepDaemon** [bmFtZQ/edge-frfox#127]
### Description
Include clear explanation of the feature and how it works.
In some SS/images shown there is spacing above the tabs area but in real use there is none.

**Include screenshot / video recording if possible.**
![image](https://github.com/bmFtZQ/edge-frfox/assets/88533953/1561006d-f922-4d0f-8bbb-7299b7fcad99)

**Comment by bmFtZQ** [comment]
This is intentional as Edge does the same thing when maximised or in fullscreen. If you want to add the space back to the top of the window, you can delete the two `--uc-tab-top-margin: 0px !important;` lines at the top of `chrome/global/tabbar.css`

**Comment by SleepDaemon** [comment]
OK thanks, btw https://youtu.be/0QVs1jVuA8c this repo is featured in this video
