### ISSUE TITLE
Profile drop down menu box is too big.

### ISSUE THREAD

**Issue by Spacellary** [bmFtZQ/edge-frfox#129]
### Description
Clicking the 3 dots then your account/profile brings a menu with a few options, but the box for this menu is very oversized and goes past the options. This wasn't the case in the previous versions for me. Tested in both Nightly and stable Firefox.

**Include screenshot / video recording if possible:**

![image](https://github.com/bmFtZQ/edge-frfox/assets/39604793/5176e5cc-55bf-4f23-8631-71b7f0f1ce40)

**The menu from the movable profile icon remains correct:**

![image](https://github.com/bmFtZQ/edge-frfox/assets/39604793/9090d626-0e5a-4d6b-9b80-d1c48684dc60)

### Configuration
* Firefox Version: 121.0.1 (64-bit) and Nightly 123.0a1 (2024-01-10) (64-bit)
* OS: Windows 11
* Tweaks enabled: 
  * `uc.tweak.context-menu.hide-access-key`
  * `uc.tweak.disable-drag-space`
  * `uc.tweak.floating-tabs`
  * `uc.tweak.hide-forward-button`
  * `uc.tweak.hide-newtab-logo`
  * `uc.tweak.newtab-background`
  * `uc.tweak.remove-tab-separators`
  * `uc.tweak.show-tab-close-button-on-hover`
  * `uc.tweak.vertical-context-navigation`

**Comment by nikkehtine** [comment]
The menu pop up stays the same size even when navigating to a submenu, this is normal Firefox behavior

**Comment by ContinuumOperand** [comment]
Since it's redundant to have both and to make it closer to Edge, I think a tweak option to hide the Profile menu from the [...] menu then would be interesting, as Edge doesn't have that, with only the profile icon being visible.
