### ISSUE TITLE
Bringing Edge style on Unified Extensions menu

### ISSUE THREAD

**Issue by KiKaraage** [bmFtZQ/edge-frfox#131]
I tried to make the extension menu more compact. Still missing several things tho, like shortcut to open addons.mozilla.com, but i think it's as close as I can get

![gambar](https://github.com/bmFtZQ/edge-frfox/assets/10529881/1b8b8380-5982-44ea-b655-b4897aaf3567)

![gambar](https://github.com/bmFtZQ/edge-frfox/assets/10529881/24f5b55a-76c8-483d-8be1-a9892e6f03fe)

```
#unified-extensions-view {
  --uei-icon-size: 17px;

  & > .panel-header {
    display: none !important;
        & + toolbarseparator {
      border: none !important;
      margin: 2px 2px 2px 2px !important;
    }
  }
  
  & .unified-extensions-item {
     margin: -5px 3px 0px 5px !important;
  }
  
  & .unified-extensions-item-message-deck {
    align: left;
  }
  
  & .unified-extensions-item-menu-button {
    list-style-image: url("chrome://global/skin/icons/more.svg") !important;
    scale: 0.7 !important;
    padding: 0 0 0 var(--arrowpanel-menuitem-margin-inline) !important;
    
    & > .toolbarbutton-icon {
      border: none !important;
    }
  }
 & overflow: hidden;
}
```

**Comment by bmFtZQ** [comment]
I've updated the menu style now. By default it uses a mix of both the Edge and Firefox style, but with the new `uc.tweak.context-menu.compact-extensions-menu` tweak, it uses the more compact Edge style.

### Before
![image](https://github.com/bmFtZQ/edge-frfox/assets/62812711/ff876c2b-d420-446a-986f-5fa1b890841e)

### After
![image](https://github.com/bmFtZQ/edge-frfox/assets/62812711/c02e57e5-86ee-4c7f-a304-c145fdb7b445)

### After (With compact extensions menu tweak)
![image](https://github.com/bmFtZQ/edge-frfox/assets/62812711/9b12766d-6050-4d57-9adb-202ee74754d9)
