### ISSUE TITLE
Checkboxes don't use proper theme

### ISSUE THREAD

**Issue by graycolorss1** [bmFtZQ/edge-frfox#133]
### Description
In the new update the check boxes use the default theme instead of the Edge theme.

![Screemshot](https://github.com/bmFtZQ/edge-frfox/assets/159735400/3dc4e05b-6fd4-40b0-99e8-427c4f9f470f)

### Configuration
* Firefox Version: 122.0.1
* OS: Windows 11

**Comment by bmFtZQ** [comment]
I think the reason for this is that Firefox uses its own default styles for the checkbox, because of this, the colour cannot be changed on its own. As far as I know, to change the colour, the entire checkbox styling would need to be rewritten (which I would prefer to avoid doing).
