### ISSUE TITLE
[BUG] Windows control (min max close) button fails on 123+ Beta/Nightly after enabling 'uc.tweak.hide-tabs-bar'

### ISSUE THREAD

**Issue by DuktigZhou** [bmFtZQ/edge-frfox#135]
### Description

[Occurs only on versions 123+ Beta/Nightly]

After enabling 'uc.tweak.hide-tabs-bar' to hide horizontal tabs, Windows control (min max close) button fails. Mouse clicks and mouse hover are invalid. Element 'titlebar-buttonbox' cannot be selected with the browser toolbox. 

Normal when 'uc.tweak.hide-tabs-bar' is disabled.

### Configuration
* Firefox Version: Firefox Beta 123.0b9/Firefox Nightly 124.0a1
* OS: Windows 11
* Tweaks enabled: 
  * uc.tweak.disable-drag-space
  * uc.tweak.floating-tabs
  * uc.tweak.hide-forward-button
  * uc.tweak.hide-tabs-bar
  * uc.tweak.remove-tab-separators
  * uc.tweak.rounded-corners
  * uc.tweak.show-tab-close-button-on-hover

**Comment by bmFtZQ** [comment]
The issue should be fixed now.
