### ISSUE TITLE
Theme Tree Style Tab (Vertical Tabs)

### ISSUE THREAD

**Issue by aspizu** [bmFtZQ/edge-frfox#136]
Could you please implement theme for [Tree Style Tab](https://github.com/piroor/treestyletab)

Edge has vertical tabs. There is a [theme existing](https://github.com/UnlimitedAvailableUsername/Edge-Mimicry-Tree-Style-Tab-For-Firefox) but it would be nice if this one has a better integrated theme.

**Comment by bmFtZQ** [comment]
I have been already experimenting with a theme for vertical tabs, but it will use Sidebery as that is the only vertical tabs extension I've actually used.

The Sidebery theme is mostly complete but I want to fix some bugs and clean up the code before releasing it. I don't know exactly when that will happen though (maybe within a week or two?).

Here is a screenshot of it so far (being mostly complete):

![Screen Shot 2024-03-18 at 10 53 40 pm](https://github.com/bmFtZQ/edge-frfox/assets/62812711/d9d033cf-c546-4e67-ab2e-4d380dcddee0)

**Comment by aspizu** [comment]
beautiful as always

**Comment by bmFtZQ** [comment]
I've added the Sidebery theme to the repository now.

![macOS_hide-tabs-bar_sidebery_dark](https://github.com/bmFtZQ/edge-frfox/assets/62812711/abda3871-18b8-4851-8bf5-67aa83dcae85)

**Comment by aspizu** [comment]
![](https://media.discordapp.net/attachments/1216842627379363924/1227564314089754695/image.png?ex=6628dd5b&is=6616685b&hm=240ef3702baaff0befe110383d7e51b2b028b740e337a6c65d7c91271c79f265&=&format=webp&quality=lossless&width=828&height=700)


This is how it looks for me.

**Comment by bmFtZQ** [comment]
You have to enable it in about:config (`uc.tweak.theme.sidebery`) if you haven't already.

This Sidebery theme is loaded using `userContent.css`, rather than loading the CSS inside Sidebery directly. So also make sure that you have updated the whole theme to the latest version.
