### ISSUE TITLE
active tab bottom corners are not rounded and not smooth at all

### ISSUE THREAD

**Issue by Kolcha** [bmFtZQ/edge-frfox#137]
### Description
both left and right bottom corners of active tab are not rounded, top corners also look "not so round"

![Screenshot_20240318_151351](https://github.com/bmFtZQ/edge-frfox/assets/947647/3f80f871-1fe9-46b5-a12c-9f4932e15633)

surprisingly, it looks fine with some older version found in [another theme](https://github.com/dracula/firefox) based on this one (that's how I found this nice project)

![Screenshot_20240318_151446](https://github.com/bmFtZQ/edge-frfox/assets/947647/713f7b9d-c773-42e9-8c24-1a79f3362a73)

### Configuration
* Firefox Version: 123.0.1
* OS: Kubuntu 22.04 (Linux with KDE), X11
* Tweaks enabled: no tweaks

### Notes:
* using High DPI (aka Retina) display, 200% scaling, no tweaks related to scaling in Firefox
* Firefox is installed for [Snap](https://snapcraft.io/firefox) (by default in Ubuntu)
* theme commit 737b81e6e643709f8bf9f3c4d246b8b6179493df

**Comment by Kolcha** [comment]
some experimentation shown that the issue is caused by some theme installed from addons.mozilla.org, disabling it fixes the issue

sorry for bothering you

**Comment by bmFtZQ** [comment]
Are you using a custom theme?

If so the theme you are using might be adding an outline around the tab. For example, in the Firefox Alpenglow theme it looks like this, with a purple outline around the tab:

![image](https://github.com/bmFtZQ/edge-frfox/assets/62812711/cedcadff-3b80-4ad1-8a46-358f9d466c1f)

Some themes might an outline around the tab that uses the same colour as the toolbar, this causes what you see here. One fix for this would be to just disable the outline by adding this code to `userChrome.css` or to a file named `custom.css` inside the `chrome` folder.

```css
#TabsToolbar {
  --lwt-tab-line-color: unset !important;
}
```

Firefox Alpenglow after disabling the outline colour:
![image](https://github.com/bmFtZQ/edge-frfox/assets/62812711/06848a5d-0b49-41ce-9df0-06081011c2af)
