### ISSUE TITLE
Add icon to "Report broken site" menu

### ISSUE THREAD

**Issue by KiKaraage** [bmFtZQ/edge-frfox#138]
I don't have this theme forked so I can't make pull request yet but here's the workaround I can share for [icons.css](https://github.com/bmFtZQ/edge-frfox/blob/main/chrome/icons/icons.css):

```
#appMenu-report-broken-site-button {
  list-style-image: url("report.svg") !important;
}

#report-broken-site-popup-mainView .panel-header>h1>span::before {
  --header-image: url("report.svg");
  --uc-enabled: 1;
}
```

**Comment by bmFtZQ** [comment]
I've added the icon to that menu item.
