### ISSUE TITLE
Use firefox theme colors for sidebery

### ISSUE THREAD

**Issue by aspizu** [bmFtZQ/edge-frfox#139]
![](https://media.discordapp.net/attachments/1216842627379363924/1227565058196770826/image.png?ex=6628de0c&is=6616690c&hm=9b6d12405a681d9936c7c69adb807c2a23a9c971391b16c7dcfaed03f22ef028&=&format=webp&quality=lossless&width=866&height=700)

**Comment by bmFtZQ** [comment]
Looks like I made a small mistake in the file, Firefox themes should be usable now.
