### ISSUE TITLE
More rounded tabs

### ISSUE THREAD

**Issue by evgeniy-harchenko** [bmFtZQ/edge-frfox#140]
### Description
I installed latest theme version (v24.4.10), but more rounded tabs not more rounded. Is it normal? Should I do something to switch them on?

![image](https://github.com/bmFtZQ/edge-frfox/assets/42656259/aee21e2b-6739-4e16-8720-cca9dca5ba10)

### Configuration
* Firefox Version: 125.0
* OS: KDE Neon 6.0

**Comment by bmFtZQ** [comment]
The more rounded tabs are enabled with the rounded browser corners tweak (`uc.tweak.rounded-corners`).

**Comment by evgeniy-harchenko** [comment]
Yes, now it works as it should.

P.S. Many thanks for beautiful theme!
