### ISSUE TITLE
Add ability to remove close button

### ISSUE THREAD

**Issue by m3957** [bmFtZQ/edge-frfox#144]
### Description
I don't update my EdgeFrfox frequently so I was stuck with v24.2.4. In this version and before, Linux support for the hide tabs toolbar tweak wasn't there. My Firefox window looked like this:

![Capture d’écran du 2024-04-21 09-14-10](https://github.com/bmFtZQ/edge-frfox/assets/86982093/f50e9719-e427-49d6-8a40-f3e2eb4305ad)

In v24.2.13, the next version, where Linux support was properly added for the hide tabs toolbar tweak, my Firefox window now looks like this:

![Capture d’écran du 2024-04-21 09-14-40](https://github.com/bmFtZQ/edge-frfox/assets/86982093/19b14f6e-165a-4ccf-bc6f-d0b7ca6b0872)

It would be nice to have a feature to hide the close button and the drag space after it. I don't want to delete the entire Linux/GTK part of `hide-tabs.css` just to remove my close button.

**Comment by bmFtZQ** [comment]
Now the window controls can be hidden using the `uc.tweak.hide-tabs-bar.no-window-controls` tweak (either enabled with the existing tweak or on its own):

![Screenshot showing Firefox window with the hide tabs bar tweak, with window controls removed.](https://github.com/bmFtZQ/edge-frfox/assets/62812711/51a1db05-be13-49d5-b5e8-84c05cde9917)
