### ISSUE TITLE
Password manager pop up windows have their upper and lower border cut

### ISSUE THREAD

**Issue by xJusteen47** [bmFtZQ/edge-frfox#153]
### Description
password pop ups appear like this

**Include screenshot / video recording if possible.**
![Screenshot 2024-08-15 151605](https://github.com/user-attachments/assets/73a30b36-c4ec-4444-bdbe-1390ed2c70e5)

### Configuration
* Firefox Version: 129.0.1 (64 bit)
Windows 11
* Tweaks enabled: 
 none

**Comment by bmFtZQ** [comment]
I've now added a fix for this, which can be seen in the latest commit.
