### ISSUE TITLE
The Pop Menu (when you press Alt key) is broken

### ISSUE THREAD

**Issue by SleepDaemon** [bmFtZQ/edge-frfox#156]
### Description
Refer to screenshot below

![image](https://github.com/user-attachments/assets/15920fde-57f0-47b6-a557-8a156125cf54)

### Configuration
* Firefox Version: v130
* OS: Windows 11
* Tweaks enabled: 
![image](https://github.com/user-attachments/assets/52602910-a30f-4eef-acf0-81a3a3c3d08e)

**Comment by bmFtZQ** [comment]
I can't seem to replicate this on my installation.
![image](https://github.com/user-attachments/assets/da6cf638-5791-42fe-876d-1679abc638a6)

Do you have the latest commit of the theme installed ([direct link](https://github.com/bmFtZQ/edge-frfox/archive/refs/heads/main.zip))?

Are there any additional customisations you have applied?
