### ISSUE TITLE
Tab dirty border

### ISSUE THREAD

**Issue by mongmeow** [bmFtZQ/edge-frfox#159]
### Description
White border appears around the tab when ` uc.tweak.floating-tabs` is turned on. (appears only in light mode)

![a](https://github.com/user-attachments/assets/48ffa497-b8a0-4593-8ca6-37b291dbed1d)

### Configuration
* Firefox Version: 131.0
* OS: Windows 10
* Tweaks enabled: 
  * uc.tweak.floating-tabs
  * uc.tweak.hide-forward-button
  * uc.tweak.hide-newtab-logo
  * uc.tweak.newtab-background
  * uc.tweak.remove-tab-separators
  * uc.tweak.show-tab-close-button-on-hover

**Comment by bmFtZQ** [comment]
This should be fixed in the latest commit.
