### ISSUE TITLE
Update control buttons to new Microsoft Edge style

### ISSUE THREAD

**Issue by tobyisawesome** [bmFtZQ/Edge-FrFox#16]
Current Edge-FrFox control buttons:
![image](https://user-images.githubusercontent.com/71511385/149847668-07ad9809-0601-42b2-b711-1e8973c91753.png)
Current Microsoft Edge control buttons:
![image](https://user-images.githubusercontent.com/71511385/149847711-c306086b-9cd4-4c77-8bc9-8029cc0b8ca0.png)

**Comment by bmFtZQ** [comment]
implemented in the latest commit
