### ISSUE TITLE
There is an empty space right of menu icon ( i.e. the three dot )

### ISSUE THREAD

**Issue by zh-y-h** [bmFtZQ/edge-frfox#165]
### Description
There is an empty space located right of menu icon of tool bar, as below.

![图片](https://github.com/user-attachments/assets/aa9a760d-851e-40e9-a2d0-8f36eb20bd29)

### Configuration
* Firefox Version: 133.0b1
* OS: windows 11 24h2 2161
* Tweaks enabled: Does not.
  * 
  *

**Comment by bmFtZQ** [comment]
This should be fixed in the latest commit.
