### ISSUE TITLE
Pixel-thin line

### ISSUE THREAD

**Issue by rh1nehart** [bmFtZQ/edge-frfox#169]
### Description
Pixel-thin line between tabbar and browser content

**Include screenshot / video recording if possible.**
![image](https://github.com/user-attachments/assets/a3a2465d-e8f4-4954-9b1f-0b8de4c442be)
![image](https://github.com/user-attachments/assets/a8746585-cc1e-41d5-bafb-81e67d2577a5)

### Configuration
* Firefox Version: 132 Stable 
* OS: Windows 11
* Tweaks enabled: 
  * `uc.tweak.context-menu.compact-extensions-menu`
  * `uc.tweak.disable-drag-space`
  * `uc.tweak.floating-tabs`
  * `uc.tweak.remove-tab-separators`
  * `uc.tweak.rounded-corners`

**Comment by bmFtZQ** [comment]
I cannot seem to replicate this on my system, do you have any other styles/customisations enabled?

![image](https://github.com/user-attachments/assets/dcc0e12a-efe1-4b9c-b8a6-64c45daf03d1)

**Comment by rh1nehart** [comment]
Only
```
#alltabs-button {
display: none !important;
}

.tabbrowser-tab {
	margin-right: 2px !important;
}
```

**Comment by rh1nehart** [comment]
Never mind. I fixed this by refreshing Firefox to default settings
