### ISSUE TITLE
The "Site Information" and "Site Permissions" buttons overlap.

### ISSUE THREAD

**Issue by tobyisawesome** [bmFtZQ/Edge-FrFox#17]
![](https://i.imgur.com/byhky9S.gif)

**Comment by bmFtZQ** [comment]
response in issue #4:

> This was intentional as I can't seem to select the lock button based on if the permissions button is showing. I thought it looked better to make it like this rather than making the lock icon shorter for all pages, even if the permissions button is not being shown.

**Comment by tobyisawesome** [comment]
Okay.
