### ISSUE TITLE
Highlight of address bar matches is too light

### ISSUE THREAD

**Issue by phayz** [bmFtZQ/Edge-FrFox#2]
I really like this style. The standard Firefox look is OK, but I think this is better. The icons help provide extra polish.

Now for my issue...

When I enter text in the address bar, matching URLs from my history are listed and the first one highlighted. The highlight colour is too light IMO. Can I make this a little darker?

<img width="825" alt="image" src="https://user-images.githubusercontent.com/438816/112938486-0bc73700-916d-11eb-975a-8c8d70eecedc.png">

**Comment by bmFtZQ** [comment]
Try the newest version of [`chrome/global/variables.css`](https://github.com/bmFtZQ/Edge-FrFox/blob/main/chrome/global/variables.css)

If you want it even darker the variable name is `--autocomplete-popup-highlight-background`

**Comment by phayz** [comment]
Wow! Thank you for an incredibly fast response! I'll try the newest version.

**Comment by phayz** [comment]
Strange... now it's looks even stranger. I replaced the original `variables.css` with the latest edition and restarted Firefox.

<img width="825" alt="image" src="https://user-images.githubusercontent.com/438816/112977031-ee0fc700-9198-11eb-985f-39ed9a470642.png">

**Comment by bmFtZQ** [comment]
Can you try re-downloading the full project from source code?
