### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by Pixel556** [bmFtZQ/edge-frfox#20]
The theme doesn't work, I expected it to work, but it didn't.
I'm running Windows 11 Build 22000.527.
How can i fix this?

**Comment by bmFtZQ** [comment]
What are the **exact** steps you took to install the theme?

Did you:

1. Download and unzip the theme
2. locate your Firefox profile and move the `chrome` folder from the theme inside
3. change the `about:config` values in the readme

What Firefox version?

**Comment by Pixel556** [comment]
Can it work on WaterFox?

**Comment by bmFtZQ** [comment]
This theme only works on Firefox with the Proton design (89+) and I only test it with Firefox so I doubt this theme will work with WaterFox.

I recommend updating to a modern version of Firefox if you want to use this theme, and if you want to switch back to the older style Firefox theme later, try looking at [r/FirefoxCSS](https://www.reddit.com/r/FirefoxCSS) for a Photon (<=88) styled theme.

**Comment by ikkqqstudio** [comment]
> This theme only works on Firefox with the Proton design (89+) and I only test it with Firefox so I doubt this theme will work with WaterFox.
> 
> I recommend updating to a modern version of Firefox if you want to use this theme, and if you want to switch back to the older style Firefox theme later, try looking at [r/FirefoxCSS](https://www.reddit.com/r/FirefoxCSS) for a Photon (<=88) styled theme.

mine i test if really works with waterfox or not, when i tested it worked for me, okay why when i press search bar on the top, search bar on the top looks a bit weird
