### ISSUE TITLE
[Feature Request] Adding mica material to titlebar/tabbar

### ISSUE THREAD

**Issue by SilverMarcs** [bmFtZQ/edge-frfox#21]
Would you consider adding mica support to the tabbar? It already seems to work with [this](https://github.com/KibSquib48/MicaFox) mod, so should be possible

**Comment by bmFtZQ** [comment]
I plan on adding it eventually, but Windows is not the operating system I use daily, so this might take some time until I can add this feature.

**Comment by bmFtZQ** [comment]
This is now implemented as a tweak: `uc.tweak.win11-mica`, just follow the instructions in the [readme](https://github.com/bmFtZQ/edge-frfox#mica-tweak-instructions-windows-11-only).
