### ISSUE TITLE
Is there any plan to support the right-click menu style?

### ISSUE THREAD

**Issue by aecra** [bmFtZQ/edge-frfox#22]

**Comment by bmFtZQ** [comment]
If you mean adding acrylic/transparency I'm not sure it is possible to do that with Firefox CSS tweaks, but I am planning on adding something that will look more like the Windows 11 context menu in the future.

**Comment by EdwardLangdon** [comment]
If I am right, Your commit should have made the Context menu something similar to Edge's Context menu. But it isn't.
