### ISSUE TITLE
Padding Issue in Navigation Bar

### ISSUE THREAD

**Issue by EdwardLangdon** [bmFtZQ/edge-frfox#23]
The Below needs to be fixed. Firefox 100, Windows 11.

![image](https://user-images.githubusercontent.com/101938856/168205136-4c68f72f-179a-4bed-a520-4a5141750322.png)

**Comment by EdwardLangdon** [comment]
@bmFtZQ Can you tell anything about this ?

**Comment by bmFtZQ** [comment]
The permissions button has less padding on the left so the icon can be placed closer to the site information button.

**Comment by bmFtZQ** [comment]
As I said in issue #4 there isn't really an alternative as CSS selectors can only select downwards in the page layout.

The site information button cannot be selected based on if the permissions button is displayed, so the only solutions I can find are:

1. Site information button is always shorter on one side.
2. The button overlaps slightly when the permissions button is displayed.

I found that solution 2 was better than the first, so that is what the theme uses. Although I would welcome anyone to find a better solution and submit a pull request.

**Comment by EdwardLangdon** [comment]
Why not try using Option 2 and make a commit then ?

**Comment by bmFtZQ** [comment]
> Why not try using Option 2 and make a commit then ?
>
> By this atleast we don't have permissions icon in the field of Padlock.

Option 2 is what the theme already uses. The button and the icon overlapping is what I meant.

Although I guess there could be a third solution and that would be to add more space between the icons but that didn't look as nice when the icons are not being hovered over imo.

|Solution 2 (Current)|Solution 3 (more spacing)|
|-|-|
|![Solution2](https://user-images.githubusercontent.com/62812711/168617000-553dbbfc-ddb6-4ae5-9bc0-2afcc4fa6ef6.png)|![Solution3](https://user-images.githubusercontent.com/62812711/168617225-68119203-beaf-4c5c-9572-78d25569ac8e.png)|
|![Solution2 animation](https://user-images.githubusercontent.com/62812711/168619961-4c491fe3-3b57-4b4b-957c-17cf66283659.gif)|![Solution3 animation](https://user-images.githubusercontent.com/62812711/168620058-04700d69-6ae0-4d36-ac36-8380f5cf06e0.gif)|

and why I didn't use solution 1:
![Screen Shot 2022-05-16 at 22 19 30](https://user-images.githubusercontent.com/62812711/168618332-15ee6a3f-5b83-4f39-8058-4cef728a7881.png)

**Comment by EdwardLangdon** [comment]
Great to know.

>So releasing tags/versions for each update instead of just downloading the full repository?

Yeah, Because It would be easy to follow new Changes and update accordingly.

Do you know of a easier way to update the CSS instead of downloading again, everytime ?

**Comment by bmFtZQ** [comment]
> Do you know of a easier way to update the CSS instead of downloading again, everytime ?

You could use a simple script to download the theme and move it to the chrome folder automatically using `curl` and `tar`. Although it downloads the latest commit instead of the latest release because that is easier to do.


macOS/Linux Shell script (.sh file):
```sh
#!/bin/sh
# temp dir used to store downloaded/extracted files before copying
TEMPCHROMEDIR="/tmp/userchrome"
# find profile dir in about:profiles "root directory"
PROFILEDIR="/Users/USERNAME/Library/Application Support/Firefox/Profiles/xxxxxxxx.default-release"
# file to download
UPDATEURL="https://github.com/bmFtZQ/edge-frfox/archive/refs/heads/main.tar.gz"

# make temp dir
mkdir -p "$TEMPCHROMEDIR"
# download file using curl
curl -Lo "$TEMPCHROMEDIR/theme.tar.gz" "$UPDATEURL"
# extract archive into temp dir
tar -xf "$TEMPCHROMEDIR/theme.tar.gz" --strip 1 -C "$TEMPCHROMEDIR"
# remove existing chrome dir
rm -rf "$PROFILEDIR/chrome"
# copy chrome folder to profile
cp -r "${TEMPCHROMEDIR}/chrome" "$PROFILEDIR/chrome"
# remove temp dir
rm -rf "$TEMPCHROMEDIR"
```

Windows Batch script (.bat file):
```batch
@REM temp dir used to store downloaded/extracted files before copying
set TEMPCHROMEDIR=%Temp%\userchrome
@REM find profile dir in about:profiles "root directory"
set PROFILEDIR=C:\Users\USERNAME\AppData\Roaming\Mozilla\Firefox\Profiles\xxxxxxxx.default-release
@REM file to download
set UPDATEURL=https://github.com/bmFtZQ/edge-frfox/archive/refs/heads/main.tar.gz

@REM make temp dir
mkdir %TEMPCHROMEDIR%
@REM download file using curl
curl -Lo "%TEMPCHROMEDIR%\theme.tar.gz" "%UPDATEURL%"
@REM extract archive into temp dir
tar -xf "%TEMPCHROMEDIR%\theme.tar.gz" --strip 1 -C "%TEMPCHROMEDIR%"
@REM remove existing chrome dir
rmdir "%PROFILEDIR%\chrome\" /Q/S
@REM copy chrome folder to profile
xcopy "%TEMPCHROMEDIR%\chrome" "%PROFILEDIR%\chrome\" /E/Y
@REM remove temp dir
rmdir "%TEMPCHROMEDIR%" /Q/S
```

So you can save the script to a file and run it when you want to update the theme. The script is commented and explains what each step does.

**Comment by EdwardLangdon** [comment]
As, The Main Issue is solved and doing releases is dependant on you. I am closing this issue.

**Comment by bmFtZQ** [comment]
I've published the first new release now.

> I think it's better to use Git for this purposes instead.

I didn't use git for the script because that isn't installed by default on Windows and macOS.
