### ISSUE TITLE
Tab Separator

### ISSUE THREAD

**Issue by EdwardLangdon** [bmFtZQ/edge-frfox#24]
I know this CSS is for replicating Edge's UI in FIrefox, But Do you consider about removing the Tab Separator because other tabs will seem unified and cleaner in terms of UI or helping me in removing that for myself alone ?

**Comment by EdwardLangdon** [comment]
@bmFtZQ I am sort of adapted to this. Can you delete this issue and #25 and #27 ?

Please - https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue ?

**Comment by bmFtZQ** [comment]
I've added this to the "tweaks" customisation in the latest commit. To enable it, create a new key in `about:config` `uc.tweak.remove-tab-separators` and make sure it is set to `true`, then restart the browser.
