### ISSUE TITLE
New commit is breaking buttons

### ISSUE THREAD

**Issue by EdwardLangdon** [bmFtZQ/edge-frfox#29]
![image](https://user-images.githubusercontent.com/101938856/173065502-e2a4ce5e-067f-468f-97b6-bd870506c7a6.png)

As you see in the image, The new commit has breaken things on my fork. I am not sure if this is because of you or my fork.

And Mica also doesn't apply even though my settings are :

![image](https://user-images.githubusercontent.com/101938856/173065782-9ccfb6b7-85cb-4180-ab32-2c5494fc870a.png)

**Comment by EdwardLangdon** [comment]
Which Theme are you referring to ?

**Comment by bmFtZQ** [comment]
> Which Theme are you referring to ?

System theme - auto

**Comment by EdwardLangdon** [comment]
Sorry, Where should I look for it ?

**Comment by bmFtZQ** [comment]
> Sorry, Where should I look for it ?

In `about:addons` > Themes

![Screen Shot 2022-06-10 at 20 50 03](https://user-images.githubusercontent.com/62812711/173068127-86b36c07-8e91-40af-82b6-26d7a35722d2.png)

**Comment by EdwardLangdon** [comment]
But the buttons appear even though I have mica turned off.

**Comment by EdwardLangdon** [comment]
Okay, I just did as what you instructed it's working but I don't want my theme to be system rather adapt to the ones I set customly in new release.

**Comment by EdwardLangdon** [comment]
I am closing this issue as the buttons are fixed in the referenced commit.
