### ISSUE TITLE
Tab-label isn't vertically centered 

### ISSUE THREAD

**Issue by Deatrg** [bmFtZQ/Edge-FrFox#3]
Great thanks for your working, I just really like this theme and it's already my daily driver theme. When using this, I found that the label of the tab is not vertically centered which is strange.

![图片](https://user-images.githubusercontent.com/49280415/114274835-d6ff8d80-9a52-11eb-91e7-2cbe03aaa58f.png)

So I found the related code in the file name "tabbar.css".
![图片](https://user-images.githubusercontent.com/49280415/114274923-280f8180-9a53-11eb-9a5d-3a7e7a2c7c5c.png)

I change set the value of margin-top to zero which make the label of tab become vertically centered.

![图片](https://user-images.githubusercontent.com/49280415/114275013-7f155680-9a53-11eb-9e31-742172ce251f.png)

Are there some reasons that value have to be -2px? If there were, is there any other ways to make the label vertically centered?
 Thanks for your working, again.

**Comment by bmFtZQ** [comment]
Would you be able to try the newest commit to `tabbar.css`?

**Comment by Deatrg** [comment]
I have tried and it works, thanks.
