### ISSUE TITLE
Additional Theme similar to edge

### ISSUE THREAD

**Issue by EdwardLangdon** [bmFtZQ/edge-frfox#30]
While using the `System-Auto` theme, It is indeed replicating Edge's Tab bar color as like in below image:

![image](https://user-images.githubusercontent.com/101938856/173071977-3e8484a3-65f4-4192-a136-71bdac49421f.png)

But when using Dark theme as below. The Dark theme of Firefox is applied.
![image](https://user-images.githubusercontent.com/101938856/173072041-9620de9b-c29a-4155-b869-88ccb96a1680.png)

The second theme is not so good. I want the first tab bar's color when I enable Dark Theme.

I am suggesting that you create a theme of the first one and list it along other themes if possible or publish a theme in AMO.

**Comment by bmFtZQ** [comment]
The 'Light' and 'Dark' themes now have custom colours applied. Mica should also work with those themes but sometimes can be glitchy when applying a theme other than the system default. If that happens just restart Firefox.

**Comment by EdwardLangdon** [comment]
So, The Glitch happens if I use Mica ?

**Comment by bmFtZQ** [comment]
> So, The Glitch happens if I use Mica ?

The glitch can only happen with Mica enabled. But it only seems to happen rarely, it happens most often when using a website theme that doesn't match the toolbar (eg. light website theme, dark toolbar theme). The glitch doesn't happen with the 'System default - auto' theme though.

But I don't think this glitch can be fixed with CSS though.

**Comment by EdwardLangdon** [comment]
I have Mica enabled. Tested some sites with things that you mentioned in the bracket.

But it works flawlessly. I think it happens only if you have the settings as below : 

![image](https://user-images.githubusercontent.com/101938856/173084270-2601b0fc-31a1-4a0c-8168-19b130ac02ca.png)

or the vice versa in the above.

**Comment by EdwardLangdon** [comment]
![image](https://user-images.githubusercontent.com/101938856/173089060-a0545af4-394b-4f42-9ae6-f7cc0b60e111.png)

I think this made this horrible. Can you check yourself ?

**Comment by bmFtZQ** [comment]
This is something that can't be fixed with CSS, it is either a bug in Firefox or Windows. I might have to just limit Mica to the 'System default - auto' theme. It seems too glitchy otherwise.

**Comment by EdwardLangdon** [comment]
Also the Text in the popup windows too such as : 

![image](https://user-images.githubusercontent.com/101938856/173090813-dc90afaf-b1f2-4979-b7bf-234229f5432a.png)

![image](https://user-images.githubusercontent.com/101938856/173090921-9d723659-f0b7-4a20-984c-a57c4e746089.png)

Well, I will try this in Mica and tell you what happens.

**Comment by EdwardLangdon** [comment]
I turned off Mica and it's fixed. I am not gonna use Mica and wait until Firefox uses even if it takes a decade or so.

**Comment by EdwardLangdon** [comment]
By the way, Thanks for making a Awesome CSS

**Comment by bmFtZQ** [comment]
> Just one last request. Apply theme to the following windows too and sidebar menus that appear when you press `Ctrl+B`,etc.

I'll see what I can do, the library window seems like it can be themed.

> I hope that you will find an issue to the Mica Problem.

For the Mica issue I will just disable it for any theme other than 'System default - auto' as that seemed to work perfectly fine.

**Comment by EdwardLangdon** [comment]
Anything regarding the sidebar menu ?
