### ISSUE TITLE
Explanation for a tweak

### ISSUE THREAD

**Issue by EdwardLangdon** [bmFtZQ/edge-frfox#32]
`uc.tweak.force-tab-colour` - What does this tweak actually do ?

I am confused by your Wording in Readme. A detailed explanation with images would be great.

**Comment by bmFtZQ** [comment]
`uc.tweak.force-tab-colour` forces the tab background colour to be the same colour as the navbar background colour. It is useful for themes that set a separate tab background colour (such as Proton themes that use a different tab background colour to increase contrast.)

OFF:
![Screen Shot 2022-06-11 at 15 42 30](https://user-images.githubusercontent.com/62812711/173178741-62111201-fb6c-4cd2-8d28-8761d0f5dfff.png)

ON:
![Screen Shot 2022-06-11 at 15 42 52](https://user-images.githubusercontent.com/62812711/173178745-fc932fa1-1b9d-407f-a6f2-c4a56c89e0af.png)

But can cause some readability issues with some themes (such as white text on white background):
![Screen Shot 2022-06-11 at 15 47 29](https://user-images.githubusercontent.com/62812711/173178797-8e058a9a-035b-4bc4-ab4b-30db5a0ac466.png)


I'll probably make a small image showing the difference between on and off.

**Comment by bmFtZQ** [comment]
I've made the explanation less confusing and added a small image to show the difference between on and off:

![image](https://user-images.githubusercontent.com/62812711/173180773-8e7fe0b1-6cfd-421d-922e-2d606d923761.png)
