### ISSUE TITLE
Improvements to Firefox Badge in Nav Bar

### ISSUE THREAD

**Issue by EdwardLangdon** [bmFtZQ/edge-frfox#33]
https://user-images.githubusercontent.com/101938856/173175119-43bd8815-57d6-4244-a2b2-abb6510cc0a3.mp4

If you see the video, The Box (Padding) around firefox has blended with the color of the navigation bar. I get the thing that it is similar to edge but edge has a Vertical bar separating the badge and URL.

Better to fix it.

**Comment by EdwardLangdon** [comment]
This issue applies to every Firefox page such as Extensions, Preferences, etc.

**Comment by bmFtZQ** [comment]
I've added a separator between the urlbar box and url label now:

![Screen Shot 2022-06-11 at 18 41 48](https://user-images.githubusercontent.com/62812711/173184606-45e2a182-e4fb-4b09-8fad-cd77b5da3849.png)

![Screen Shot 2022-06-11 at 18 41 51](https://user-images.githubusercontent.com/62812711/173184610-2b9e8a81-af42-4faa-8e45-ab4499ab630d.png)
