### ISSUE TITLE
Add more icons to context menu

### ISSUE THREAD

**Issue by bmFtZQ** [bmFtZQ/edge-frfox#36]
Add icons for empty menu items:

![context menu showing empty menuitems](https://user-images.githubusercontent.com/62812711/174487944-15e9745e-7b2b-4bb2-bc98-fc310103752d.png)

**Comment by EdwardLangdon** [comment]
I think this can be closed

**Comment by VitalSkib** [comment]
Hi. 
Any way to add Zoom icon (under the hamburger/three-dot menu)..? 
Can't do it for some reason. 
Thanks.

![2022-07-28 Mozilla Firefox](https://user-images.githubusercontent.com/43848892/181587244-74c80ea1-f25a-4b2e-90f7-2f4a0182e8a2.png)

**Comment by bmFtZQ** [comment]
> Hi. Any way to add Zoom icon (under the hamburger/three-dot menu)..? Can't do it for some reason. Thanks.
> 
> ![2022-07-28 Mozilla Firefox](https://user-images.githubusercontent.com/43848892/181587244-74c80ea1-f25a-4b2e-90f7-2f4a0182e8a2.png)

Sorry for not seeing this before, but the zoom button doesn't have an icon element, so something similar to the context menus would need to be applied (using background-images). I wont be adding that icon as Edge doesn't have it either.
