### ISSUE TITLE
Replicate Edge's Context menu as is without Mica support.

### ISSUE THREAD

**Issue by EdwardLangdon** [bmFtZQ/edge-frfox#37]

**Comment by bmFtZQ** [comment]
Do you mean with the top row of buttons changed to a vertical list like the mac version?

This is how the theme is supposed to look in Windows/Linux at the moment (except those extra icons haven't been added yet):
![image](https://user-images.githubusercontent.com/62812711/174628380-51a55876-1a9e-4057-88b8-b7f14d405118.png)

Mozilla removed the group of horizontal icons in the macOS version of Firefox 89:
![Screen Shot 2022-06-20 at 21 44 23](https://user-images.githubusercontent.com/62812711/174629049-a768ec78-131a-451f-8ab8-81d886c38928.png)

**Comment by EdwardLangdon** [comment]
The Context Menu of Edge in Windows 11 :

![image](https://user-images.githubusercontent.com/101938856/174724550-9ac867cf-9e73-48ac-8754-b60e755699f4.png)

The Context Menu of Firefox in Windows 11 : 

![image](https://user-images.githubusercontent.com/101938856/174724657-9fb266df-6c81-4191-8ee1-aafdfa9db440.png)

So, Is there a way to totally redesign the menu like edge which is similar to MacOS ?

**Comment by adam-adrian** [comment]
Maybe you want look at https://github.com/Guerra24/Firefox-UWP-Style

**Comment by EdwardLangdon** [comment]
I like the UWP style's concept but not everything is good except these : 

![image](https://user-images.githubusercontent.com/101938856/174730339-b5d89c54-7399-4967-a3a5-f923930e3615.png)

![image](https://user-images.githubusercontent.com/101938856/174730515-851448df-880e-4e95-b7ce-3bf3466e7e07.png)

Maybe this be added but may conflict when using cross-platform.

But the issue is mainly regarding replicating the context menu.

@adam-adrian  Would you mind sharing the Context menu of the CSS you linked ?

**Comment by adam-adrian** [comment]
I don't know but there's one way to get it in the issues

**Comment by bmFtZQ** [comment]
Try updating the theme now. The context menu should look like this:

![Screen Shot 2022-06-23 at 00 56 32](https://user-images.githubusercontent.com/62812711/175097496-499e355c-c971-4754-b1a5-1c7f7287b791.png)

For the vertically arranged `#context-navigation` group enable the tweak: `uc.tweak.vertical-context-navigation`

**Comment by EdwardLangdon** [comment]
This is working as intended. Thanks.
