### ISSUE TITLE
Titlebar button box container with Mica enabled should respect the full height of tabs on Windows 11

### ISSUE THREAD

**Issue by tobyisawesome** [bmFtZQ/edge-frfox#38]
This issue is now present in the latest commit of Edge-Frfox.

![](https://i.imgur.com/rmbds5u.png)

For a good comparison, here's the current height of the titlebar buttons in current Edge Canary:

![](https://i.imgur.com/iTZZ356.png)

_Originally posted by @tobyisawesome in https://github.com/bmFtZQ/edge-frfox/issues/14#issuecomment-1163081311_

[bmFtZQ](https://github.com/bmFtZQ) has stated in response to this issue:
> The only way to fix this (that I know of) is to hide the theme's icons and rely on the ones drawn by Windows. Since those icons are located in a fixed position the buttons have to be moved, otherwise you end up with misaligned buttons/icons:
> 
> ![Screen Shot showing misaligned window control button](https://user-images.githubusercontent.com/62812711/175044785-336be91a-150c-4fc0-95eb-59d85799a817.png)

**Comment by bmFtZQ** [comment]
Closing this due to Mica no longer being supported.
