### ISSUE TITLE
Use the latest design of Edge's Rounded Tabs

### ISSUE THREAD

**Issue by tobyisawesome** [bmFtZQ/edge-frfox#39]
Edge Canary seems to have a faint white outline and bolded text for the selected tab. I propose for Edge-Frfox to use this current design rather than the older one it uses now.

Top screenshot is Edge Canary, and the bottom is Edge-Frfox.
![](https://i.imgur.com/VLkDDIs.png)
![](https://i.imgur.com/njXJHyl.png)

**Comment by bmFtZQ** [comment]
I've updated the style now:

![Screen Shot 2022-06-23 at 03 37 06](https://user-images.githubusercontent.com/62812711/175122494-65eeb9aa-f7fa-42b2-b63a-dbde38501823.png)

![Screen Shot 2022-06-23 at 03 37 24](https://user-images.githubusercontent.com/62812711/175122508-a016ec3f-82a5-4e5c-92ed-1355f4307ff6.png)
