### ISSUE TITLE
The hovered and pressed background of urlbar's left icon overlays  another icon.

### ISSUE THREAD

**Issue by Deatrg** [bmFtZQ/Edge-FrFox#4]
When there are two icons in the left side of urlbar, the pressed backgroud will overlay the another icon and the second icon's pressed background seems not showing at the right place.

![图片](https://user-images.githubusercontent.com/49280415/114289472-d0046980-9aaa-11eb-9eee-c2c2d56c8e64.png)

![图片](https://user-images.githubusercontent.com/49280415/114289473-d266c380-9aaa-11eb-8215-11b481a71173.png)

**Comment by bmFtZQ** [comment]
This was intentional as I can't seem to select the lock button based on if the permissions button is showing. I thought it looked better to make it like this rather than making the lock icon shorter for all pages, even if the permissions button is not being shown.

**Comment by Deatrg** [comment]
Oh, I see. I might be too OCD for that, hhhh
