### ISSUE TITLE
Tweak: Mica in address bar row instead of only the tab row for default style. (Windows 11 Explorer-style tabs)

### ISSUE THREAD

**Issue by tobyisawesome** [bmFtZQ/edge-frfox#40]
Currently, the look of edge-frfox with Mica enabled (and floating tabs disabled) only has Mica in the tab row, with the address bar row being completely opaque. 

Some may want for there to also be transparency in the address bar row too, without it being limited to just the tab row. 

I propose for there to be a tweak that enables for the address bar row to be a lighter shade of Mica. I don't suggest for this to replace the current functionality, but I suggest for it to be an alternative tweak to those who may want it.

Here's an example where Mica extends under the tab row, where there are two shades of Mica. This screenshot is from File Explorer on the Beta channel of the Windows Insider Program.
![File Explorer Tabs](https://user-images.githubusercontent.com/71511385/175085885-4acb1c1a-d84b-4393-9fb2-ca9f9a21050f.png)

**Comment by bmFtZQ** [comment]
Closing this due to Mica being no longer supported.
