### ISSUE TITLE
Add a tweak to enable acrylic on context menu

### ISSUE THREAD

**Issue by maicol07** [bmFtZQ/edge-frfox#41]
Firefox menu is like this (old version):

![](https://user-images.githubusercontent.com/9463142/175103181-47e38489-11f5-4989-8810-f1c8af6b4072.png)

While Edge is like this:

![](https://user-images.githubusercontent.com/9463142/175103426-b0e8f0bd-7cda-401f-9193-0bf502200e94.png)

The main difference is Acrylic. Can you add it?

Thanks

---

This might be achieved with the new [`backdrop-filter: blur()`](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter) css property.

**Comment by bmFtZQ** [comment]
This isn't possible unfortunately, `backdrop-filter` will not apply to elements that are rendered as their own windows. Firefox can only blur it's own content, with the popup menu Firefox isn't rendering anything behind it so there is nothing to blur.

![Screen Shot 2022-06-23 at 02 18 38](https://user-images.githubusercontent.com/62812711/175114574-ea45253f-405a-4575-945e-c3f1d1544389.png)
