### ISSUE TITLE
The Context Menu font could be smaller? 

### ISSUE THREAD

**Issue by marioparty26** [bmFtZQ/edge-frfox#42]
The Context Menu looks near perfect now with the new edge icons.
However, the font is a little larger than how it appears on edge.
Could you make the context menu font slightly smaller?

- ### Current Font Size:

![image](https://user-images.githubusercontent.com/47206815/175559513-59ca10d0-b115-49c5-a4b6-f0f527d2889e.png)

- ### Font Size on Edge:

![image](https://user-images.githubusercontent.com/47206815/175559766-807de43d-a1e3-49c3-9bdb-cfdcf5f9dcb7.png)

**Comment by bmFtZQ** [comment]
I've added this as a tweak because on my installations, the Edge context menu has the same font-size as the theme's context menu. So if you want to make it smaller, enable the tweak: `uc.tweak.smaller-context-menu-text` (which will use the default font-size that Firefox sets.)
