### ISSUE TITLE
Make close tab button always visible

### ISSUE THREAD

**Issue by adam-adrian** [bmFtZQ/edge-frfox#46]
In Edge, the close tab button always visible by default. I think it will simple to implement directly or make a option in Firefox config page.

**Comment by bmFtZQ** [comment]
I've added a tweak that will show the close button when hovering over the tab as that will make it easier to read smaller sized tabs: `uc.tweak.show-tab-close-button-on-hover`

![image](https://user-images.githubusercontent.com/62812711/179023269-221a4acd-04b5-41b3-94b3-76135f1870bb.png)
