### ISSUE TITLE
Private mode indicator invisible?

### ISSUE THREAD

**Issue by iGameEveryDay6** [bmFtZQ/edge-frfox#47]
For some reason even with the tweak enabled the private mode indicator isn't visible.
![image](https://user-images.githubusercontent.com/83013894/175817317-ffeeddfa-1cea-478f-a54b-0f22c94e4e59.png)
![image](https://user-images.githubusercontent.com/83013894/175817325-7839fe8f-9181-4fe3-b988-b1586df9df3b.png)

**Comment by surapunoyousei** [comment]
If you not turn on Firefox sync, it's not displayed.

**Comment by bmFtZQ** [comment]
This should be fixed now.

**Comment by EdwardLangdon** [comment]
What tweak should I use to hide this Generic Icon when not signed in ?
