### ISSUE TITLE
port to chromium?

### ISSUE THREAD

**Issue by deverebor** [bmFtZQ/edge-frfox#48]
Can any way we make an port to chromium base?

**Comment by EdwardLangdon** [comment]
`UserChrome.css` is only meant for Firefox to customize it. In Chrome, You can only change the in-built themes. As it is already Chromium, You can't do anyting about that.

**Comment by Hidetoshi6721** [comment]
> This wouldn't be possible as chromium does not support `userChrome.css` or anything equivalent. But even if it did, that would require a full rewrite of the theme, as all the CSS Selectors/IDs/Class names are specific to Firefox.

That's one of the best things about Firefox - customisation =)
