### ISSUE TITLE
Right click and search bar bug

### ISSUE THREAD

**Issue by Am86Shekari** [bmFtZQ/Edge-FrFox#5]
**1.** 

      I love your Firefox theme but they have this bug when i right click in Ubuntu:
![image](https://user-images.githubusercontent.com/80213487/114296604-83785880-9ac1-11eb-975d-d7d51378448b.png)

**2.** 

      and they have this bag when i want to search something (you can see 2 magnifier icon in search box) :
![image](https://user-images.githubusercontent.com/80213487/114296668-cc301180-9ac1-11eb-92ba-99ef3cd00b6b.png)

**3.** 

     and this is other bug i found in dark mode (you can see they have no border for tabs) :
![image](https://user-images.githubusercontent.com/80213487/114296637-9db23680-9ac1-11eb-8c13-0ec46b2f3731.png)

**Comment by bmFtZQ** [comment]
I wasn't able to replicate any of the issues on a clean install of Ubuntu. But for bug 1 and 2 I have made changes that *might* fix them. I don't know what would be causing bug 3 though, but try downloading the whole theme again from the newest source.

**Comment by Am86Shekari** [comment]
I restart my firefox and then  don't see this bugs sorry for I did't tell you that before
