### ISSUE TITLE
Full screen mode shows rounded corners and window border if Mica is enabled

### ISSUE THREAD

**Issue by CherryQuartzio** [bmFtZQ/edge-frfox#51]
If `uc.tweak.win11-mica` is set to true and full screen mode is entered, a transparent window border will show around the display with rounded corners as if the browser is still in windowed mode. This does not happen if full screen mode is entered when the browser window is maximized, or the Mica tweak is disabled. Also, the window control icon for minimize, restore, and close disappear when the browser is in focus

![Screenshot 2022-07-13 202002](https://user-images.githubusercontent.com/85609395/178891030-845d5b10-7b81-47cf-a3aa-4e7b5b7461be.png)

**Comment by EdwardLangdon** [comment]
It might happen if your Browser profile is corrupted. Try applying the CSS on a new profile. I am telling this as it happened to me too.

**Comment by CherryQuartzio** [comment]
Already tried it with a new profile using the latest commit on both the installer and Microsoft Store version of the browser. Still the same for me

**Comment by bmFtZQ** [comment]
Closing this due to Mica being no longer supported.
