### ISSUE TITLE
Context Menu and Bookmark Toolbar Folder Context Menu not highling text

### ISSUE THREAD

**Issue by mthuc** [bmFtZQ/Edge-FrFox#7]
### Issue
When opening the right click context menu or the bookmarks in a folder on the bookmark toolbar, the text is not highlighted when hovering over the text of the folder or context menu.

### Information
**Operating System**: Windows 10
**Browser**: Firefox 88

**Comment by bmFtZQ** [comment]
For now you can fix this by enabling `layout.css.color-mix.enabled` in `about:config`

Seems like Mozilla changed the variable used for the selection background to use the new [`color-mix()`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix()) value.

**Comment by mthuc** [comment]
Thanks @bmFtZQ ! Closing this since it can be fixed with the `about:config` flag.
