### ISSUE TITLE
Default Tab Container Underline No Longer Hidden

### ISSUE THREAD

**Issue by krisnielsen** [bmFtZQ/Edge-FrFox#8]
A recent update seems to have changed the class used for the tab underline created by multi-account containers. This leads to duplicate underlines and the underline persisting when the tab is active.

Previously it was `.tab-bottom-line`

Now it is `.tab-context-line`

**Comment by bmFtZQ** [comment]
Should be fixed now

**Comment by krisnielsen** [comment]
Perfect, thank you!
