### ISSUE TITLE
Spacing between the first tab missing on Firefox 110

### ISSUE THREAD

**Issue by SafariBat** [bmFtZQ/edge-frfox#80]
**Description**
On Firefox 110+ the spacing to the left of the first tab seems to be missing.

**Include screenshot / video recording if possible.**
![Screenshot](https://user-images.githubusercontent.com/107957769/216801664-84d8e740-b93d-4f73-be7b-5d029ebfa265.png)

**Configuration**
- Firefox Version: 110.0
- OS: Windows 11

**Comment by bmFtZQ** [comment]
It seems like Firefox 110 got rid of some tab attributes:

```css
[beforeselected-visible],
[first-visible-tab],
[last-visible-tab],
[before-multiselected],
[beforehovered],
[afterhovered]
```

The `[first-visible-tab]` attribute was being used to apply extra spacing at the start of the first tab. But I've replaced it with a `:first-of-type` selector.
