### ISSUE TITLE
After upgrading to Firefox 111.0, Firefox Home is stuck in light theme

### ISSUE THREAD

**Issue by hmmmstarstruck** [bmFtZQ/edge-frfox#85]
After upgrading to Firefox 111, the Firefox home page has reverted to light theme and even with settings switched to dark theme it is still stuck. When I launch Firefox in troubleshooting mode (thus disabling edge-frfox) the home page is correctly themed.

- Firefox Version: 111.0
- OS: Windows 11 10.0.23403.1001

**Comment by bmFtZQ** [comment]
Can you try the newest version and see if it works now?

**Comment by upseguest** [comment]
> Can you try the newest version and see if it works now?

Thank you, it worked! I downloaded directly from latest source code btw, not the latest release.
