### ISSUE TITLE
Add a switch to set horizontal or vertical tabs

### ISSUE THREAD

**Issue by juzijun233** [bmFtZQ/edge-frfox#86]
**Description**
I love the vertical tab mode in edge, I was looking for an extension in firefox to do it, but there are still horizontal tabs, I wish there was a switch to turn off the horizontal tabs

**Include screenshot / video recording if possible.**

**Comment by bmFtZQ** [comment]
The newest version of the theme now has a new tweak: `uc.tweak.hide-tabs-bar`

This tweak hides the tab bar and allows you to use any third-party extension for vertical tabs support:

![Screenshot showing hide tabs bar tweak](https://github.com/bmFtZQ/edge-frfox/assets/62812711/ed677500-8105-42aa-b8e5-2ac74e91b075)
