### ISSUE TITLE
Profile icon on Firefox Nightly is offset

### ISSUE THREAD

**Issue by upseguest** [bmFtZQ/edge-frfox#87]
**Description**
Edge-frfox, when enabled on firefox nightly has a weird issue where the profile icon is offset unusually.
![image](https://user-images.githubusercontent.com/104295975/227626326-24cef552-291b-4cee-8989-cd773d0c2f74.png)

**Configuration**
- Firefox Version: 113.0a1
- OS: Windows 11 dev channel 23419

**Comment by bmFtZQ** [comment]
This should be fixed in the newest commit of the theme.
