### ISSUE TITLE
Firefox Nightly 92 - Some buttons are misaligned in the address bar

### ISSUE THREAD

**Issue by ZetaStormy** [bmFtZQ/Edge-FrFox#9]
Hello, I really like this theme and I use it everyday, but since the latest Firefox Nightly version that updates to Firefox 92, the "Bookmark this page", "Page actions" button and "Protections" button are misaligned in the address bar. Video is attached to see more about this behaviour.

https://user-images.githubusercontent.com/56933557/126190993-234c6b78-870c-4401-af6d-b3ff553c647e.mp4

**Comment by bmFtZQ** [comment]
It should be fixed now in the newest commits.

**Comment by ZetaStormy** [comment]
It is fixed now, thanks :D
