### ISSUE TITLE
Firefox looks weird when enabling uc.tweak.win11-mica

### ISSUE THREAD

**Issue by foursplaysroblox** [bmFtZQ/edge-frfox#93]
**Description**
Include clear explaination of bug and how to reproduce.

Everytime I enable uc.tweak.win11-mica in about:config it looks weird and it looks goofy

**Include screenshot / video recording if possible.**
![image](https://github.com/bmFtZQ/edge-frfox/assets/82078139/0563b9eb-9ce3-42b7-bb72-edec71d10a33)

then this if I minimize
![image](https://github.com/bmFtZQ/edge-frfox/assets/82078139/c2651208-eef0-46b2-b0cc-9fc6900a8bf5)

**Configuration**
- Firefox Version: 115.0 (64-bit) Beta
- OS: Windows 11 Insider Build 25393 Canary Build

**Comment by bmFtZQ** [comment]
Mica was broken in the Firefox 115 update, this means that the theme will no longer be able to use Mica so it has been removed.
