### ISSUE TITLE
Checkbox not rendering properly

### ISSUE THREAD

**Issue by Barpheli** [bmFtZQ/edge-frfox#97]
**Description**
The appearance of checkbox elements was strange after I installed the theme. They seem to be double-checked.
 
**Include screenshot / video recording if possible.**

![Screenshot from 2023-08-03 21-46-54](https://github.com/bmFtZQ/edge-frfox/assets/141359526/b7f424b3-8787-4a2e-b42e-9f1f9d27d66e)

**Configuration**
- Firefox Version: 116.0
- OS: Linux Mint - Cinnamon

**Comment by evgeniy-harchenko** [comment]
As a temporary workaround delete _chrome/icons/checkmark.svg_

**Comment by bmFtZQ** [comment]
This should be fixed now in the latest commit of the theme.
