### ISSUE TITLE
Mica can't work on firefox nightly on win11 canary

### ISSUE THREAD

**Issue by cyntlab** [bmFtZQ/edge-frfox#98]
I had already enabled mica in about:config and mica-for-everyone, but mica still can't work since firefox nightly 116.

**Configuration**
- Firefox Version: nightly 118a1
- OS: Windows 11 canary build 25926

**Comment by n1ckoates** [comment]
Mozilla removed the `-moz-win-borderless-glass` value for `appearance` in Firefox 117, which transparency in this theme (and many others) relies on to work. You can use Firefox ESR which still supports it.

**Comment by bmFtZQ** [comment]
Unfortunately, Mica doesn't work in Firefox any more as Mozilla removed the CSS values necessary to use it in Firefox 115. Mica has been removed from the theme now.
