### ISSUE TITLE
All toolbar icons showing up as black. Probably after latest FF117 update.

### ISSUE THREAD

**Issue by marioparty26** [bmFtZQ/edge-frfox#99]
**Description**
All toolbar icons are appearing as black in dark theme in Windows 10 today.
Not a very perfect screenshot but I hope this explains the issue:
![image](https://github.com/bmFtZQ/edge-frfox/assets/47206815/f895c081-ad82-4293-af50-50ffdbb15228)

**Configuration**
- Firefox Version: 117
- OS: Windows 10

**Comment by bmFtZQ** [comment]
Is `svg.context-properties.content.enabled` set to `true` in `about:config`?
